name: Test and Build

on:
  push:
    branches:
      - master
      - release

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install testing dependencies
        run: pip install -r requirements/test.txt
      - name: Run tests
        run: ./tests/tests.py

  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the package
        run: ./build.sh
