name: Test, Build, and Release

on:
  push:
    branches:
      - master
      - release

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install testing dependencies
        run: pip install -r requirements/test.txt
      - name: Run tests
        run: ./tests/tests.py

  build:
    runs-on: macOS-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Get the version number
        run: echo ::set-env name=VERSION::$(./payload/msda --version 2>&1)
      - name: Build the package
        run: ./build.sh
      - name: Upload built package
        uses: actions/upload-artifact@master
        with:
          name: "Mac Set Default Apps.pkg"
          path: "./Mac Set Default Apps v$VERSION.pkg"

  # release:
  #   runs-on: macOS-latest
  #   needs: [test, build]
  #   steps:
