name: Test, Build, and Release

on:
  push:
    branches:
      - master
      - release

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install testing dependencies
        run: pip install -r requirements/test.txt
      - name: Run tests
        run: ./tests/tests.py

  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get the version number
        id: get_version
        run: echo "##[set-output name=version;]$(./payload/msda --version 2>&1)"
      - name: Build the package
        run: ./build.sh
      - name: Upload built package
        uses: actions/upload-artifact@master
        with:
          name: ${{ format('Mac Set Default Apps v{0}.pkg', steps.get_version.outputs.version) }}
          path: ${{ format('./Mac Set Default Apps v{0}.pkg', steps.get_version.outputs.version) }}

  # release:
  #   runs-on: macOS-latest
  #   needs: [test, build]
  #   steps:
