name: Test and Build

on:
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Install testing dependencies
        run: pip install -r requirements/test.txt
      - name: Run tests
        run: ./tests/tests.py
    
  build:
    runs-on: macOS-latest
    steps:
      - name: Build the package
        run: ./build.sh
