name: Test, Build, and Release

on:
  push:
    branches:
      - master
      - release

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install testing dependencies
        run: pip install -r requirements/test.txt
      - name: Run tests
        run: ./tests/tests.py

  build:
    runs-on: macOS-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Build the package
        run: ./build.sh
      - name: Upload built package
        uses: actions/upload-artifact@master
        with:
          name: "Mac Set Default Apps v1.0.0.pkg"
          path: "./Mac Set Default Apps v1.0.0.pkg"

  # release:
  #   runs-on: macOS-latest
  #   needs: [test, build]
  #   steps:
